const fs = require('fs');
const path = require('path');

const newTranslations = {
    fr: {
        public_nav: {
            home: "Accueil",
            about: "À propos",
            services: "Services",
            contact: "Contact",
            getStarted: "Commencer",
            navigation: "Navigation",
            yourAccount: "Votre Compte",
            login: "Se connecter",
            register: "Créer un compte",
            needHelp: "Besoin d'aide ?"
        },
        landing: {
            consultant: "Consultant",
            heroTitleLine1: "We Unlock Your Business",
            heroTitleLine2: "Opportunity",
            heroDesc: "Establish your vision and value proposition and turn them into testable prototypes.",
            createAccountLink: "Créer un compte",
            usersWorldwide: "users worldwide",
            balance: "BALANCE",
            featuresTitle: "Fonctionnalités",
            featuresHeading: "Une nouvelle façon de gérer votre quotidien",
            featuresDesc: "Profitez d'une expérience bancaire simplifiée. De l'envoi d'argent instantané à la gestion de votre épargne, tout se fait en quelques clics et en toute sécurité.",
            feat1Title: "Sécurité Bancaire Avancée",
            feat1Desc: "Vos envois de fonds, réceptions et épargnes sont protégés...",
            feat2Title: "Support Client 24/7",
            feat2Desc: "Une question sur un virement ou votre demande de crédit ?...",
            loansTitle: "Prêts",
            loansHeading: "Obtenez un prêt rapide en quelques clics",
            loansDesc: "Que ce soit pour un nouveau projet immobilier, un achat urgent...",
            loanSimulate: "Simuler mon prêt",
            whyUsTitle: "Pourquoi Nous Choisir",
            whyUsHeading: "Des services pensés pour vos besoins.",
            whyUsDesc: "Retrouvez tous les outils indispensables d'une banque en ligne moderne rassemblés dans une interface intuitive et hautement sécurisée.",
            learnMore: "En Savoir Plus",
            downloadApp: "Download Banking App",
            downloadDesc: "Experience freedom right at your fingertips...",
            testimonialsTitle: "Témoignages",
            testimonialsHeading: "Ce que nos clients disent de nous",
            testimonialsDesc: "Découvrez comment notre plateforme a transformé la gestion...",
            faqTitle: "FAQ",
            faqHeading: "Frequently Asked Questions",
            quickLinks: "Liens Rapides",
            subscribeNews: "Souscrire à la Newsletter",
            subscribeDesc: "Rejoignez notre liste de diffusion...",
            enterEmail: "Entrez votre email"
        },
        about: {
            story: "Notre Histoire",
            title: "Redéfinir la Banque Moderne pour vous.",
            desc: "Chez Financer, nous croyons qu'une banque doit être transparente...",
            valuesTitle: "Nos Valeurs Fondamentales",
            val1: "Transparence Totale",
            val1Desc: "Pas de frais cachés, pas de mauvaises surprises...",
            val2: "Sécurité Maximale",
            val2Desc: "Votre argent et vos données sont protégés...",
            val3: "Accessibilité Globale",
            val3Desc: "Gérez vos finances de n'importe où dans le monde...",
            activeClients: "Clients Actifs",
            supportedCountries: "Pays Supportés",
            transactionsInfo: "Transactions",
            supportOption: "Support Client"
        },
        servicesPage: {
            tag: "Nos Services",
            title: "Tout ce dont vous avez besoin, Réuni au même endroit.",
            desc: "De la gestion de votre quotidien au suivi de vos investissements...",
            learnMoreArrow: "En savoir plus",
            callToActionTitle: "Prêt à changer de banque ?",
            callToActionDesc: "Rejoignez-nous en moins de 3 minutes et ouvrez votre compte gratuitement avec un IBAN instantané.",
            openFreeAccount: "Ouvrir mon compte gratuit"
        },
        contactPage: {
            tag: "Contact",
            title: "Nous sommes là pour vous Accompagner.",
            desc: "Oubliez les attentes interminables. Contactez nos conseillers...",
            callUs: "Appelez-nous",
            callDesc: "Besoin d'aide immédiate ? Nos conseillers sont à votre écoute.",
            whatsapp: "WhatsApp",
            whatsappDesc: "Échangez avec nous rapidement par message, où que vous soyez.",
            emailUs: "Envoyez un e-mail",
            emailDesc: "Pour toute demande détaillée ou envoi de documents.",
            hours: "Nos services clients sont ouverts 24 heures sur 24, 7 jours sur 7."
        }
    },
    en: {
        public_nav: { home: "Home", about: "About", services: "Services", contact: "Contact", getStarted: "Get Started", navigation: "Navigation", yourAccount: "Your Account", login: "Login", register: "Create an Account", needHelp: "Need Help?" },
        landing: { consultant: "Consultant", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision and value proposition and turn them into testable prototypes.", createAccountLink: "Create an Account", usersWorldwide: "users worldwide", balance: "BALANCE", featuresTitle: "Features", featuresHeading: "A new way to manage your everyday", featuresDesc: "Enjoy a simplified banking experience...", feat1Title: "Advanced Bank Security", feat1Desc: "Your remittances are protected...", feat2Title: "24/7 Support", feat2Desc: "A question about a transfer?...", loansTitle: "Loans", loansHeading: "Get a fast loan in clicks", loansDesc: "Whether for a new real estate project...", loanSimulate: "Simulate my loan", whyUsTitle: "Why Choose Us", whyUsHeading: "Services designed for you.", whyUsDesc: "Find all the essential tools...", learnMore: "Learn More", downloadApp: "Download Banking App", downloadDesc: "Experience freedom right at your fingertips...", testimonialsTitle: "Testimonials", testimonialsHeading: "What our clients say", testimonialsDesc: "Discover how our platform...", faqTitle: "FAQ", faqHeading: "Frequently Asked Questions", quickLinks: "Quick Links", subscribeNews: "Subscribe Newsletter", subscribeDesc: "Join our mailing list...", enterEmail: "Enter your email" },
        about: { story: "Our Story", title: "Redefining Modern Banking for you.", desc: "At Financer, we believe a bank should be...", valuesTitle: "Our Core Values", val1: "Total Transparency", val1Desc: "No hidden fees...", val2: "Maximum Security", val2Desc: "Your money and data are protected...", val3: "Global Accessibility", val3Desc: "Manage your finances from anywhere...", activeClients: "Active Clients", supportedCountries: "Supported Countries", transactionsInfo: "Transactions", supportOption: "Customer Support" },
        servicesPage: { tag: "Our Services", title: "Everything you need, in one place.", desc: "From day-to-day management to tracking...", learnMoreArrow: "Learn more", callToActionTitle: "Ready to switch banks?", callToActionDesc: "Join us in under 3 minutes...", openFreeAccount: "Open my free account" },
        contactPage: { tag: "Contact", title: "We are here to support you.", desc: "Forget endless waiting...", callUs: "Call us", callDesc: "Need immediate help?...", whatsapp: "WhatsApp", whatsappDesc: "Chat with us quickly...", emailUs: "Email us", emailDesc: "For detailed requests...", hours: "Our customer service is open 24/7." }
    },
    es: {
        public_nav: { home: "Inicio", about: "Sobre nosotros", services: "Servicios", contact: "Contacto", getStarted: "Empezar", navigation: "Navegación", yourAccount: "Tu Cuenta", login: "Iniciar Sesión", register: "Crear Cuenta", needHelp: "¿Necesitas ayuda?" },
        landing: { consultant: "Consultor", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision and value proposition...", createAccountLink: "Crear una cuenta", usersWorldwide: "usuarios mundiales", balance: "SALDO", featuresTitle: "Funciones", featuresHeading: "Nueva forma de gestionar el día a día", featuresDesc: "Disfruta de experiencia bancaria simplificada...", feat1Title: "Seguridad Bancaria", feat1Desc: "Protección total...", feat2Title: "Soporte 24/7", feat2Desc: "Preguntas y respuestas...", loansTitle: "Préstamos", loansHeading: "Préstamos rápidos", loansDesc: "Para tu proyecto inmobilario...", loanSimulate: "Simular préstamo", whyUsTitle: "Por Qué Nosotros", whyUsHeading: "Servicios para ti.", whyUsDesc: "Herramientas esenciales...", learnMore: "Descubrir Más", downloadApp: "Download Banking App", downloadDesc: "Experience freedom...", testimonialsTitle: "Testimonios", testimonialsHeading: "Lo que dicen de nosotros", testimonialsDesc: "Descubre nuestra plataforma...", faqTitle: "FAQ", faqHeading: "Preguntas Frecuentes", quickLinks: "Enlaces", subscribeNews: "Newsletter", subscribeDesc: "Lista de correo...", enterEmail: "Tu email" },
        about: { story: "Nuestra Historia", title: "Redefiniendo el Banco Moderno para ti.", desc: "En Financer, creemos que...", valuesTitle: "Nuestros Valores", val1: "Transparencia", val1Desc: "Sin cargos ocultos...", val2: "Seguridad Máxima", val2Desc: "Protección total de tu dinero...", val3: "Accesibilidad", val3Desc: "Gestiona desde cualquier lugar...", activeClients: "Clientes Activos", supportedCountries: "Países", transactionsInfo: "Transacciones", supportOption: "Soporte al cliente" },
        servicesPage: { tag: "Nuestros Servicios", title: "Todo lo que necesitas, en un lugar.", desc: "Gestión día a día y más...", learnMoreArrow: "Saber más", callToActionTitle: "¿Listo para cambiar de banco?", callToActionDesc: "Únete en 3 minutos...", openFreeAccount: "Abrir cuenta gratuita" },
        contactPage: { tag: "Contacto", title: "Estamos aquí para acompañarte.", desc: "Olvida las largas esperas...", callUs: "Llámanos", callDesc: "¿Ayuda inmediata?...", whatsapp: "WhatsApp", whatsappDesc: "Habla con nosotros rápidamente...", emailUs: "Envía un correo", emailDesc: "Para detalles...", hours: "Nuestro servicio está abierto 24/7." }
    },
    de: { public_nav: { home: "Startseite", about: "Über uns", services: "Dienstleistungen", contact: "Kontakt", getStarted: "Loslegen", navigation: "Navigation", yourAccount: "Ihr Konto", login: "Anmelden", register: "Konto erstellen", needHelp: "Brauchen Sie Hilfe?" }, landing: { consultant: "Berater", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision...", createAccountLink: "Konto erstellen", usersWorldwide: "Benutzer weltweit", balance: "SALDO", featuresTitle: "Funktionen", featuresHeading: "Eine neue Art, Ihren Alltag zu verwalten", featuresDesc: "Genießen Sie ein vereinfachtes...", feat1Title: "Erweiterte Sicherheit", feat1Desc: "Ihre Gelder sind geschützt...", feat2Title: "24/7 Support", feat2Desc: "Haben Sie eine Frage?...", loansTitle: "Kredite", loansHeading: "Erhalten Sie schnell einen Kredit", loansDesc: "Ob für ein neues Projekt...", loanSimulate: "Kredit simulieren", whyUsTitle: "Warum Wir", whyUsHeading: "Dienstleistungen für Ihre Bedürfnisse", whyUsDesc: "Alle wesentlichen Tools...", learnMore: "Mehr Erfahren", downloadApp: "Download Banking App", downloadDesc: "Freiheit direkt an Ihren Fingerspitzen...", testimonialsTitle: "Erfahrungsberichte", testimonialsHeading: "Was unsere Kunden sagen", testimonialsDesc: "Entdecken Sie, wie unsere Plattform...", faqTitle: "FAQ", faqHeading: "Häufig gestellte Fragen", quickLinks: "Schnelllinks", subscribeNews: "Newsletter abonnieren", subscribeDesc: "Tragen Sie sich ein...", enterEmail: "Ihre E-Mail" }, about: { story: "Unsere Geschichte", title: "Modernes Banking für Sie neu definieren.", desc: "Wir bei Financer glauben...", valuesTitle: "Unsere Grundwerte", val1: "Volle Transparenz", val1Desc: "Keine versteckten Gebühren...", val2: "Maximale Sicherheit", val2Desc: "Ihr Geld und Ihre Daten...", val3: "Globale Erreichbarkeit", val3Desc: "Verwalten Sie Ihre Finanzen von überall...", activeClients: "Aktive Kunden", supportedCountries: "Unterstützte Länder", transactionsInfo: "Transaktionen", supportOption: "Kundensupport" }, servicesPage: { tag: "Unsere Dienste", title: "Alles was Sie brauchen, an einem Ort.", desc: "Von der täglichen Verwaltung...", learnMoreArrow: "Mehr erfahren", callToActionTitle: "Bereit die Bank zu wechseln?", callToActionDesc: "Treten Sie uns in unter 3 Minuten bei...", openFreeAccount: "Kostenloses Konto eröffnen" }, contactPage: { tag: "Kontakt", title: "Wir sind hier, um Sie zu unterstützen.", desc: "Vergessen Sie langes Warten...", callUs: "Rufen Sie uns an", callDesc: "Sofortige Hilfe nötig?...", whatsapp: "WhatsApp", whatsappDesc: "Chatten Sie mit uns...", emailUs: "E-Mail senden", emailDesc: "Für detaillierte Anfragen...", hours: "Unser Kundenservice ist rund um die Uhr geöffnet." } },
    it: { public_nav: { home: "Home", about: "Chi siamo", services: "Servizi", contact: "Contatti", getStarted: "Inizia", navigation: "Navigazione", yourAccount: "Il Tuo Conto", login: "Accedi", register: "Crea un conto", needHelp: "Serve aiuto?" }, landing: { consultant: "Consulente", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision...", createAccountLink: "Crea un conto", usersWorldwide: "utenti nel mondo", balance: "SALDO", featuresTitle: "Funzionalità", featuresHeading: "Un nuovo modo per gestire il quotidiano", featuresDesc: "Goditi un'esperienza semplificata...", feat1Title: "Sicurezza Bancaria", feat1Desc: "I tuoi fondi sono protetti...", feat2Title: "Supporto 24/7", feat2Desc: "Hai una domanda?...", loansTitle: "Prestiti", loansHeading: "Ottieni un prestito veloce", loansDesc: "Per un nuovo progetto...", loanSimulate: "Simula prestito", whyUsTitle: "Perché Noi", whyUsHeading: "Servizi pensati per te", whyUsDesc: "Trova gli strumenti essenziali...", learnMore: "Scopri di più", downloadApp: "Download Banking App", downloadDesc: "Sperimenta la libertà...", testimonialsTitle: "Testimonianze", testimonialsHeading: "Cosa dicono i nostri clienti", testimonialsDesc: "Scopri la nostra piattaforma...", faqTitle: "FAQ", faqHeading: "Domande Frequenti", quickLinks: "Link Rapidi", subscribeNews: "Iscriviti alla Newsletter", subscribeDesc: "Unisciti alla nostra lista...", enterEmail: "La tua email" }, about: { story: "La Nostra Storia", title: "Ridefinire la Banca Moderna per te.", desc: "In Financer crediamo...", valuesTitle: "I Nostri Valori", val1: "Trasparenza Totale", val1Desc: "Nessuna commissione nascosta...", val2: "Massima Sicurezza", val2Desc: "I tuoi soldi sono protetti...", val3: "Accessibilità Globale", val3Desc: "Gestisci le tue finanze...", activeClients: "Clienti Attivi", supportedCountries: "Paesi Supportati", transactionsInfo: "Transazioni", supportOption: "Supporto Clienti" }, servicesPage: { tag: "I Nostri Servizi", title: "Tutto ciò di cui hai bisogno, in un solo posto.", desc: "Dalla gestione quotidiana...", learnMoreArrow: "Scopri di più", callToActionTitle: "Pronto a cambiare banca?", callToActionDesc: "Unisciti a noi in meno di 3 minuti...", openFreeAccount: "Apri conto gratuito" }, contactPage: { tag: "Contatti", title: "Siamo qui per aiutarti.", desc: "Dimentica le lunghe attese...", callUs: "Chiamaci", callDesc: "Aiuto immediato?...", whatsapp: "WhatsApp", whatsappDesc: "Chatta con noi...", emailUs: "Inviaci un'email", emailDesc: "Per richieste dettagliate...", hours: "Il nostro servizio clienti è aperto 24/7." } },
    ro: { public_nav: { home: "Acasă", about: "Despre", services: "Servicii", contact: "Contact", getStarted: "Începe", navigation: "Navigare", yourAccount: "Contul Tău", login: "Autentificare", register: "Creare cont", needHelp: "Ai nevoie de ajutor?" }, landing: { consultant: "Consultant", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision...", createAccountLink: "Creare cont", usersWorldwide: "utilizatori", balance: "SOLD", featuresTitle: "Funcționalități", featuresHeading: "Un nou mod de a gestiona...", featuresDesc: "Experiență simplificată...", feat1Title: "Securitate", feat1Desc: "Fondurile sunt protejate...", feat2Title: "Suport 24/7", feat2Desc: "Ai întrebări?...", loansTitle: "Credite", loansHeading: "Obține un credit rapid", loansDesc: "Pentru noul tău proiect...", loanSimulate: "Simulare", whyUsTitle: "De ce noi", whyUsHeading: "Servicii gândite pentru tine", whyUsDesc: "Toate instrumentele esențiale...", learnMore: "Află mai multe", downloadApp: "Download Banking App", downloadDesc: "Experiența libertății...", testimonialsTitle: "Testimoniale", testimonialsHeading: "Ce spun clienții noștri", testimonialsDesc: "Descoperă platforma noastră...", faqTitle: "FAQ", faqHeading: "Întrebări frecvente", quickLinks: "Linkuri Utile", subscribeNews: "Abonare Newsletter", subscribeDesc: "Fii la curent...", enterEmail: "Emailul tău" }, about: { story: "Povestea Noastră", title: "Redefinim Banca Modernă pentru tine", desc: "La Financer, credem că...", valuesTitle: "Valorile Noastre", val1: "Transparență Totală", val1Desc: "Fără comisioane ascunse.", val2: "Securitate Maximă", val2Desc: "Banii tăi sunt protejați.", val3: "Accesibilitate", val3Desc: "Oriunde în lume.", activeClients: "Clienți Activi", supportedCountries: "Țări", transactionsInfo: "Tranzacții", supportOption: "Suport Clienți" }, servicesPage: { tag: "Servicii", title: "Tot ce ai nevoie într-un loc", desc: "Gestionare de zi cu zi...", learnMoreArrow: "Află mai multe", callToActionTitle: "Gata să schimbi banca?", callToActionDesc: "În 3 minute ai cont...", openFreeAccount: "Deschide cont gratuit" }, contactPage: { tag: "Contact", title: "Suntem aici să te ajutăm.", desc: "Fără așteptare...", callUs: "Sună-ne", callDesc: "Ai nevoie de ajutor...", whatsapp: "WhatsApp", whatsappDesc: "Scrie-ne rapid...", emailUs: "Trimite un mail", emailDesc: "Pentru detalii...", hours: "Deschis 24/7." } },
    pl: { public_nav: { home: "Strona główna", about: "O nas", services: "Usługi", contact: "Kontakt", getStarted: "Zacznij", navigation: "Nawigacja", yourAccount: "Twoje Konto", login: "Zaloguj się", register: "Utwórz konto", needHelp: "Potrzebujesz pomocy?" }, landing: { consultant: "Konsultant", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision...", createAccountLink: "Utwórz konto", usersWorldwide: "użytkowników", balance: "SALDO", featuresTitle: "Funkcje", featuresHeading: "Nowy sposób zarządzania", featuresDesc: "Uproszczona bankowość...", feat1Title: "Bezpieczeństwo", feat1Desc: "Twoje środki...", feat2Title: "Wsparcie 24/7", feat2Desc: "Pytania?...", loansTitle: "Pożyczki", loansHeading: "Szybka pożyczka", loansDesc: "Dla nowego projektu...", loanSimulate: "Symulacja", whyUsTitle: "Dlaczego My", whyUsHeading: "Usługi dla Ciebie", whyUsDesc: "Zestaw narzędzi...", learnMore: "Więcej informacji", downloadApp: "Download Banking App", downloadDesc: "Doświadcz wolności...", testimonialsTitle: "Opinie", testimonialsHeading: "Co mówią klienci", testimonialsDesc: "Odkryj platformę...", faqTitle: "FAQ", faqHeading: "Częste pytania", quickLinks: "Szybkie linki", subscribeNews: "Newsletter", subscribeDesc: "Dołącz do nas...", enterEmail: "Twój email" }, about: { story: "Nasza historia", title: "Nowoczesna bankowość.", desc: "Wierzymy, że bank...", valuesTitle: "Nasze wartości", val1: "Pełna przejrzystość", val1Desc: "Brak ukrytych opłat.", val2: "Maksymalne bezpieczeństwo", val2Desc: "Pieniądze chronione.", val3: "Dostępność na świecie", val3Desc: "Zarządzaj skądkolwiek.", activeClients: "Aktywnych Klientów", supportedCountries: "Kraje", transactionsInfo: "Transakcje", supportOption: "Obsługa klienta" }, servicesPage: { tag: "Nasze Usługi", title: "Wszystko w jednym miejscu", desc: "Zarządzanie codzienne...", learnMoreArrow: "Więcej", callToActionTitle: "Gotowy na zmianę banku?", callToActionDesc: "Dołącz w 3 minuty...", openFreeAccount: "Otwórz darmowe konto" }, contactPage: { tag: "Kontakt", title: "Jesteśmy tu by pomóc", desc: "Zapomnij o czekaniu...", callUs: "Zadzwoń do nas", callDesc: "Szybka pomoc...", whatsapp: "WhatsApp", whatsappDesc: "Rozmawiaj szybko...", emailUs: "Wyślij email", emailDesc: "Szczegółowe prośby...", hours: "Czynne 24/7." } },
    pt: { public_nav: { home: "Início", about: "Sobre", services: "Serviços", contact: "Contacto", getStarted: "Começar", navigation: "Navegação", yourAccount: "A Sua Conta", login: "Entrar", register: "Criar Conta", needHelp: "Precisa de ajuda?" }, landing: { consultant: "Consultor", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision...", createAccountLink: "Criar uma conta", usersWorldwide: "utilizadores mundiais", balance: "SALDO", featuresTitle: "Funcionalidades", featuresHeading: "Nova forma de gerir o seu dia", featuresDesc: "Experiência bancária simplificada...", feat1Title: "Segurança Avançada", feat1Desc: "Fundos protegidos...", feat2Title: "Suporte 24/7", feat2Desc: "Perguntas?...", loansTitle: "Empréstimos", loansHeading: "Empréstimos rápidos", loansDesc: "Para um novo projeto...", loanSimulate: "Simular", whyUsTitle: "Porquê Nós", whyUsHeading: "Serviços desenhados para si", whyUsDesc: "Encontre as ferramentas...", learnMore: "Saber mais", downloadApp: "Download Banking App", downloadDesc: "Liberdade...", testimonialsTitle: "Testemunhos", testimonialsHeading: "O que dizem os clientes", testimonialsDesc: "Descubra como...", faqTitle: "FAQ", faqHeading: "Perguntas Frequentes", quickLinks: "Links Rápidos", subscribeNews: "Subscrever Newsletter", subscribeDesc: "Junte-se à lista...", enterEmail: "O seu email" }, about: { story: "A Nossa História", title: "A redefinir a Banca Moderna para si.", desc: "Acreditamos que um banco...", valuesTitle: "Os Nossos Valores", val1: "Transparência Total", val1Desc: "Sem custos ocultos...", val2: "Segurança Máxima", val2Desc: "Dinheiro e dados protegidos...", val3: "Acessibilidade", val3Desc: "Gira em qualquer parte...", activeClients: "Clientes Ativos", supportedCountries: "Países Oficiais", transactionsInfo: "Transações", supportOption: "Suporte ao Cliente" }, servicesPage: { tag: "Serviços", title: "Tudo o que precisa num só lugar.", desc: "Desde a gestão diária...", learnMoreArrow: "Saber mais", callToActionTitle: "Pronto para mudar de banco?", callToActionDesc: "Junte-se em 3 minutos...", openFreeAccount: "Abrir conta grátis" }, contactPage: { tag: "Contacto", title: "Estamos aqui para ajudar.", desc: "Esqueça as esperas...", callUs: "Ligue-nos", callDesc: "Ajuda imediata?...", whatsapp: "WhatsApp", whatsappDesc: "Fale connosco...", emailUs: "Envie-nos um email", emailDesc: "Para pedidos...", hours: "Atendimento 24/7." } },
    el: { public_nav: { home: "Αρχική", about: "Σχετικά", services: "Υπηρεσίες", contact: "Επικοινωνία", getStarted: "Ξεκινήστε", navigation: "Πλοήγηση", yourAccount: "Ο Λογαριασμός σας", login: "Σύνδεση", register: "Δημιουργία", needHelp: "Χρειάζεστε βοήθεια;" }, landing: { consultant: "Σύμβουλος", heroTitleLine1: "We Unlock Your Business", heroTitleLine2: "Opportunity", heroDesc: "Establish your vision...", createAccountLink: "Δημιουργία λογαριασμού", usersWorldwide: "παγκόσμιοι χρήστες", balance: "ΥΠΟΛΟΙΠΟ", featuresTitle: "Χαρακτηριστικά", featuresHeading: "Νέος τρόπος διαχείρισης...", featuresDesc: "Απλοποιημένη εμπειρία...", feat1Title: "Ασφάλεια Τράπεζας", feat1Desc: "Προστασία κεφαλαίων...", feat2Title: "Υποστήριξη 24/7", feat2Desc: "Κάποια ερώτηση;...", loansTitle: "Δάνεια", loansHeading: "Γρήγορο δάνειο", loansDesc: "Για το νέο σας έργο...", loanSimulate: "Προσομοίωση", whyUsTitle: "Γιατί Εμάς", whyUsHeading: "Υπηρεσίες σχεδιασμένες για εσάς", whyUsDesc: "Βρείτε τα εργαλεία...", learnMore: "Μάθετε περισσότερα", downloadApp: "Download Banking App", downloadDesc: "Απολαύστε πλήρη ελευθερία...", testimonialsTitle: "Μαρτυρίες", testimonialsHeading: "Τι λένε οι πελάτες μας", testimonialsDesc: "Ανακαλύψτε...", faqTitle: "Συχνές Ερωτήσεις", faqHeading: "Οι Ερωτήσεις σας", quickLinks: "Γρήγοροι Σύνδεσμοι", subscribeNews: "Εγγραφή στο Newsletter", subscribeDesc: "Μπείτε στη λίστα...", enterEmail: "Το email σας" }, about: { story: "Η Ιστορία μας", title: "Επαναπροσδιορίζουμε τη Σύγχρονη...", desc: "Στην Financer πιστεύουμε...", valuesTitle: "Οι Αξίες μας", val1: "Πλήρης Διαφάνεια", val1Desc: "Χωρίς κρυφές χρεώσεις...", val2: "Μέγιστη Ασφάλεια", val2Desc: "Πλήρης ασφάλεια δεδομένων. ", val3: "Σφαιρική Προσβασιμότητα", val3Desc: "Διαχείριση από οπουδήποτε...", activeClients: "Ενεργοί Πελάτες", supportedCountries: "Χώρες", transactionsInfo: "Συναλλαγές", supportOption: "Υποστήριξη" }, servicesPage: { tag: "Οι Υπηρεσίες μας", title: "Ό,τι χρειάζεστε σε ένα...", desc: "Από τη διαχείριση...", learnMoreArrow: "Μάθετε περισσότερα", callToActionTitle: "Έτοιμοι για αλλαγή τράπεζας;", callToActionDesc: "Ελάτε μαζί μας σε 3 λεπτά...", openFreeAccount: "Άνοιγμα λογαριασμού" }, contactPage: { tag: "Επικοινωνία", title: "Είμαστε εδώ για εσάς.", desc: "Ξεχάστε τις αναμονές...", callUs: "Καλέστε μας", callDesc: "Άμεση βοήθεια;...", whatsapp: "WhatsApp", whatsappDesc: "Μιλήστε μαζί μας...", emailUs: "Στείλτε email", emailDesc: "Για λεπτομέρειες...", hours: "24/7 εξυπηρέτηση." } }
};

const langs = Object.keys(newTranslations);

for (const lang of langs) {
    const filePath = path.join(__dirname, 'src', 'translations', `${lang}.json`);
    if (fs.existsSync(filePath)) {
        const fileData = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

        // Spread the new translations
        Object.assign(fileData, newTranslations[lang]);

        fs.writeFileSync(filePath, JSON.stringify(fileData, null, 4));
        console.log(`Updated ${lang}.json`);
    }
}
